### ISSUE TITLE
编译源码无法找到 fma-cloud 下的依赖

### ISSUE THREAD

**Issue by pedrogao** [TuGraph-db/tugraph-db#11]
如题，编译 tugraph-db 源码的时候，发现缺少 jwt-cpp、cpprestsdk 等依赖，其在 fma-cloud 组织下，但未在 github 上找到该组织：

```
Software: cpprestsdk
Repo: https://github.com/fma-cloud/cpprestsdk.git
License: MIT

Software: lmdb
Repo: 
License: OpenLDAP Public

Software: jwt-cpp
Repo: https://github.com/fma-cloud/jwt-cpp.git
License: MIT
```

**Comment by knightast** [comment]
Those dependency repo had be moved to environment, just use the latest package is ok, we will remove these dependency from third-party file.
