### ISSUE TITLE
bind Cypher Scheduler to python api ?

### ISSUE THREAD

**Issue by lloydzhou** [TuGraph-db/tugraph-db#142]
if bind `Cypher` `Scheduler` to `python api`, we can call `Scheduler.Eval` in `python api`.

**Comment by KingSkyLi** [comment]
You can read related documents, link address (https://tugraph.antgroup.com/doc?version=V3.3.2&id=10000000001211095), and download python-related  documents link address （https://tugraph-web-static.oss-cn-beijing.aliyuncs.com/%E6%96%87%E6%A1%A3/procedure-api/3.3.2/TuGraph-Python-Procedure-API.tar.gz）.

**Comment by lloydzhou** [comment]
i have done in my fork repository. close issue.
