### ISSUE TITLE
import csv file fail - Error parsing file memory_file_stream Error occurred at offset 0, exception detail: Missing delimiter after column 0

### ISSUE THREAD

**Issue by eddieHRS** [TuGraph-db/tugraph-db#16]
![image](https://user-images.githubusercontent.com/33120615/188415126-0b34fda0-a2c5-4b35-acc2-2cc9a14f0c58.png)

As shown in the picture. an error occours when i import relation.

content in csv like

>2022-06-17T13:56:07,999983128788335032,8275619264  
>2022-06-18T13:54:53,999991169756613250,2416174150 
>2022-06-17T13:56:07,999991169756613250,5446041392  

column 0 is time
column 1 is source
column 2 is target

Any ideas ?

**Comment by ljcui** [comment]
> 

Could you please provide the steps to reproduce this issue？

**Comment by hjk41** [comment]
DateTime type only accepts data in the format of YYYY-MM-HH hh:mm:ss, for example:
2022-06-17 13:56:07

**Comment by eddieHRS** [comment]
> DateTime type only accepts data in the format of YYYY-MM-HH hh:mm:ss, for example: 2022-06-17 13:56:07

it works, thks bro ^_^

**Comment by eddieHRS** [comment]
> > 
> 
> Could you please provide the steps to reproduce this issue？

thks, and it has been fixed now after changing dateformat. ^_^
