### ISSUE TITLE
Some graph model and schema questions

### ISSUE THREAD

**Issue by whitewum** [TuGraph-db/tugraph-db#22]
1. `Each vertex and edge must have a label.`  Can a vertex have two labels? Is there any plan to support a label-less vertex, i.e., a vertex without any label? (`TuGraph不支持创建空的nodes，不支持多labels`)
2. Is the label indexed by default as Neo4j does? Or only the properties/fields can be indexed but not the label itself. 
3. `Each graph can have its own access control configurations.` Can the admin set ACL on the property/field level (column, in the sense of RDMBS), label level(row), or only the graph level (table)?
4. Can the admin create a new Graph or GraphView (in the term of RDBMS) based on the other Graph (share with the same data)?
5. Is there any constraint/schema to specify which type/label of a vertex can connect to a given type/label of an edge?   (`constraints (only edge has)`)
6. Is dangling edge allowed? (e.g., An edge without src  vertex)
7. Is the primary key must provide in the `Create` clause? Is it indexed by default?
8. `lgraph_api::Galaxy` and `  **Scope:** whole instance.` What's the difference between `Galaxy` and  `instance`? Is instance the same as `lgraph_api::GraphDB`?

THX

**Comment by imbajin** [comment]
found some refer docs (possibly) include the question (like Q3) : 
- [release info](https://www.tugraph.org/doc?version=V3.3.0&id=10000000000658653)
- [road map](https://www.tugraph.org/doc?version=V3.3.0&id=10000000000658636)

**Comment by whitewum** [comment]
Appreciated.

Some explanations and concepts (e.g., schema, GraphDB) are given in the code comment. These basic concepts can be provided in the manual if possible.
