### ISSUE TITLE
java客户端依赖包的镜像库无法访问？

### ISSUE THREAD

**Issue by Gevygg** [TuGraph-db/tugraph-db#24]
我尝试使用/[doc-zh]/[4.client]/1.java-client.md里面描述的镜像库
<mirror>
    <id>alimaven</id>
    <name>aliyun maven</name>
    <url>http://mvn.dev.alipay.net/nexus/content/groups/public/</url>
    <mirrorOf>central</mirrorOf>
</mirror>
但是该镜像库无法访问？
该如何获取com.antgroup:tugraph-java-rpc-client:3.1.0

**Comment by ljcui** [comment]
> 

Ignore this maven setting.

Try this : `cd src/client/java/TuGraphRpcClient && sh local_build.sh `
