### ISSUE TITLE
How to use OLAP API and Graph algorithm ?

### ISSUE THREAD

**Issue by eddieHRS** [TuGraph-db/tugraph-db#26]
Hi,
After reading doc, I still be confused about how to use OLAP API and graph algorithm.
Do we have to implement their own stored procedure, compile it, upload .so file or python file to server.
Then graph algorithm(like pagerank) are available by calling this stored procedure through sdk.

^_^

**Comment by Clarkclk** [comment]
Document is being written, and you don't need to write stored procudure. 
You can refer to the pagerank_core.cpp and pagerank_procudure.cpp at plugins/cpp/ directory, and plugins/make_so.sh can help you to make so file.
