### ISSUE TITLE
镜像在哪里可以下载？

### ISSUE THREAD

**Issue by wyuxiao729** [TuGraph-db/tugraph-db#3]
看了一下docker hub上。只有两个。没有详细的说明！

**Comment by XinyuDu** [comment]
> 看了一下docker hub上。只有两个。没有详细的说明！

同问

**Comment by XinyuDu** [comment]
docker pull tugraph/tugraph-db-centos7:3.3.0

**Comment by ljcui** [comment]
> 看了一下docker hub上。只有两个。没有详细的说明！

docker pull tugraph/tugraph-db-centos7:3.3.0

docker run -d  -p 17090:7090 --name tugraph_demo tugraph/tugraph-db-centos7:3.3.0 lgraph_server -c /root/demo/movie/lgraph.json -d run

web访问 http://x.x.x.x.:17090

初始用户名和密码是：admin , 73@TuGraph

**Comment by KingSkyLi** [comment]
可以看一下官网https://www.tugraph.org/download
