### ISSUE TITLE
Could NOT find JNI (missing: JAVA_INCLUDE_PATH JAVA_INCLUDE_PATH2   JAVA_AWT_INCLUDE_PATH)

### ISSUE THREAD

**Issue by songyaheng** [TuGraph-db/tugraph-db#34]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment:**
 - OS: [e.g. Ubuntu 18.04]  mac
 - CPU: [e.g. Intel Xeon xxxx]  Intel
 - Compiler: [e.g. GCC 8.0]

**Additional context**

CMake Error at /usr/local/Cellar/cmake/3.22.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find JNI (missing: JAVA_INCLUDE_PATH JAVA_INCLUDE_PATH2
  JAVA_AWT_INCLUDE_PATH)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.22.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.22.1/share/cmake/Modules/FindJNI.cmake:382 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  src/BuildClients.cmake:18 (find_package)
  src/CMakeLists.txt:10 (include)

**Comment by ljcui** [comment]
> 

Install java 1.8 in your os environment or use `cmake -DENABLE_FULLTEXT_INDEX=OFF ` to remove the dependency on java.

BTW,  it is recommended to use `centos` or `ubuntu` to compile,  mac os has not been verified.

some references: 

https://github.com/TuGraph-db/tugraph-db/blob/master/ci/images/centos7/Dockerfile
