### ISSUE TITLE
浏览器怎么访问

### ISSUE THREAD

**Issue by bitbxj** [TuGraph-db/tugraph-db#4]
按照说明文档，启动了docker，端口号7090，但浏览器无法访问是什么原因？

**Comment by ljcui** [comment]
> 按照说明文档，启动了docker，端口号7090，但浏览器无法访问是什么原因？

docker pull tugraph/tugraph-db-centos7:3.3.0

docker run -d -p 17090:7090 --name tugraph_demo tugraph/tugraph-db-centos7:3.3.0 lgraph_server -c /root/demo/movie/lgraph.json -d run

是按照这种方式启动的吗？

**Comment by zjtaozjtw** [comment]
按照文档操作图数据库没有启动，得进到容器里面手动启动一下才能够通过浏览器访问

**Comment by bitbxj** [comment]
> > 按照说明文档，启动了docker，端口号7090，但浏览器无法访问是什么原因？
> 
> docker pull tugraph/tugraph-db-centos7:3.3.0
> 
> docker run -d -p 7070:7070 --name tugraph_demo tugraph/tugraph-db-centos7:3.3.0 lgraph_server
> 
> web 访问 http://x.x.x.x:7070
> 
> 默认用户名为 `admin`，密码为 `73@TuGraph`
it is ok ,thanks!
