### ISSUE TITLE
服务突然挂死，时间都是早上10点56分

### ISSUE THREAD

**Issue by Gevygg** [TuGraph-db/tugraph-db#45]
我这边在linux环境用docker部署了一个tugraph,9月9日早上10:56分挂了一次，今天早上10:56分又挂了一次，是后台有定时任务导致的吗？异常日志如下：
20220914025604.391: [HaStateMachine] Fail to read from Socket{id=17179869299 fd=31 addr=192.168.56.78:49486:9090} (0x7f8dc001f1d0): Connection reset by peer
20220914025604.391: [HaStateMachine] Fail to read from Socket{id=230 fd=42 addr=192.168.56.78:49492:9090} (0x7f8da401fda0): Connection reset by peer
20220914025604.391: [HaStateMachine] Fail to read from Socket{id=8589934821 fd=40 addr=192.168.56.78:49491:9090} (0x7f8da401fb60): Connection reset by peer
20220914025604.391: [HaStateMachine] Fail to read from Socket{id=34359738707 fd=38 addr=192.168.56.78:49489:9090} (0x7f8da802d350): Connection reset by peer
20220914025604.391: [HaStateMachine] Fail to read from Socket{id=25769804116 fd=28 addr=192.168.56.78:49484:9090} (0x7f8da802d590): Connection reset by peer
20220914025604.392: [HaStateMachine] Fail to read from Socket{id=34359738594 fd=32 addr=192.168.56.78:49487:9090} (0x7f8da401f4a0): Connection reset by peer
20220914025604.392: [HaStateMachine] Fail to read from Socket{id=34359738482 fd=35 addr=192.168.56.78:49488:9090} (0x7f8dc001ef90): Connection reset by peer
20220914025604.393: [HaStateMachine] Fail to read from Socket{id=25769804118 fd=30 addr=192.168.56.78:49485:9090} (0x7f8da802da10): Connection reset by peer
20220914025612.440: [StateMachine] Apply a acl request.
20220914025612.456: [StateMachine] Apply a cypher request.
20220914025612.456: [server.cypher.execution_plan] Plan cache disabled.
20220914025612.456: [cypher.execution_plan] Current Pattern Graph:
20220914025612.456: [cypher.execution_plan] (EMPTY GRAPH)
20220914025612.456: [cypher.execution_plan] Execution Plan:
20220914025612.456: [cypher.execution_plan] Produce Results
20220914025612.456: [cypher.execution_plan]     Standalone Call []

Error: signal 11:
lgraph_server[0xc99728]
/lib64/libpthread.so.0(+0xf630)[0x7f8ddd159630]
/lib64/libc.so.6(+0x154cb5)[0x7f8dda8a7cb5]
/usr/local/lib64/libstdc++.so.6(_ZNSt15basic_streambufIcSt11char_traitsIcEE6xsputnEPKcl+0x6b)[0x7f8ddcee601b]
/usr/local/lib64/libstdc++.so.6(_ZSt16__ostream_insertIcSt11char_traitsIcEERSt13basic_ostreamIT_T0_ES6_PKS3_l+0x17e)[0x7f8ddced7aae]
/usr/local/lib64/liblgraph.so(_ZN6lgraph12TryDeleteLogERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x1e4)[0x7f8dddce6304]
/usr/local/lib64/liblgraph.so(_ZN6lgraph3WalD1Ev+0x94)[0x7f8dddce3214]
/usr/local/lib64/liblgraph.so(_ZN6lgraph7KvStoreD2Ev+0x2e)[0x7f8dddb42c2e]
/usr/local/lib64/liblgraph.so(_ZN6lgraph14LightningGraph11DropAllDataEv+0x2c8)[0x7f8dddb623c8]
/usr/local/lib64/liblgraph.so(_ZN6lgraph18AccessControlledDB11DropAllDataEv+0x17)[0x7f8dddd07347]
lgraph_server(_ZN6cypher16BuiltinProcedure8DbDropDBEPNS_9RTContextEPKNS_6RecordERKSt6vectorIN6parser10ExpressionESaIS8_EERKS6_INSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaISI_EEPS6_IS3_SaIS3_EE+0x71)[0xbfec01]
lgraph_server(_ZN6cypher14StandaloneCall11RealConsumeEPNS_9RTContextE+0x433)[0xc9a553]
lgraph_server(_ZN6cypher6OpBase7ConsumeEPNS_9RTContextE+0xa)[0xbb87aa]
lgraph_server(_ZN6cypher14ProduceResults11RealConsumeEPNS_9RTContextE+0x3c)[0xc8ed3c]
lgraph_server(_ZN6cypher6OpBase7ConsumeEPNS_9RTContextE+0xa)[0xbb87aa]
lgraph_server(_ZN6cypher13ExecutionPlan7ExecuteEPNS_9RTContextE+0x7cd)[0xc5236d]
lgraph_server(_ZN6cypher9Scheduler4EvalEPNS_9RTContextERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERNS_11ElapsedTimeE+0x292)[0xb86972]
lgraph_server(_ZN6lgraph12StateMachine18ApplyCypherRequestEPKNS_13LGraphRequestEPNS_14LGraphResponseEb+0x439)[0xab1499]
lgraph_server(_ZN6lgraph12StateMachine20ApplyRequestDirectlyEPKNS_13LGraphRequestEPNS_14LGraphResponseEb+0x273)[0xab27a3]
lgraph_server(_ZN6lgraph12StateMachine9DoRequestEbPKNS_13LGraphRequestEPNS_14LGraphResponseEPN6google8protobuf7ClosureEb+0x19)[0xab3749]
lgraph_server(_ZN6lgraph12StateMachine13HandleRequestEPN6google8protobuf13RpcControllerEPKNS_13LGraphRequestEPNS_14LGraphResponseEPNS2_7ClosureEb+0xc2)[0xaa7ec2]
/usr/local/lib64/liblgraph.so(_ZN6lgraph16LGraphRPCService10CallMethodEPKN6google8protobuf16MethodDescriptorEPNS2_13RpcControllerEPKNS2_7MessageEPS8_PNS2_7ClosureE+0x85)[0x7f8dddd555d5]
lgraph_server(_ZN4brpc6policy17ProcessRpcRequestEPNS_16InputMessageBaseE+0x1159)[0x10da6b9]
lgraph_server(_ZN4brpc19ProcessInputMessageEPv+0x7)[0x10d3a67]
lgraph_server(_ZN4brpc14InputMessenger13OnNewMessagesEPNS_6SocketE+0x653)[0x10d4ac3]
lgraph_server(_ZN4brpc6Socket12ProcessEventEPv+0xd)[0xff09ad]
lgraph_server(_ZN7bthread9TaskGroup11task_runnerEl+0xc1)[0x1074121]
lgraph_server(bthread_make_fcontext+0x21)[0x1054071]
(END)

**Comment by hjk41** [comment]
Looking at the log, the crash at 9/14 occurred during handling of a Cypher request. Was the crash at 9/9 also caused by a Cypher request? If that is the case, could you post your Cypher request here?

**Comment by Gevygg** [comment]
> 

目前不再出现改问题，当时应该是服务器的资源问题导致

**Comment by Gevygg** [comment]
> 

目前不再出现该问题，当时应该是服务器本身资源不足导致
