### ISSUE TITLE
「Restful api 」only create vertex index and fail when create edge index

### ISSUE THREAD

**Issue by abstract-liu** [TuGraph-db/tugraph-db#48]
**Describe the bug**
Related api: POST http://{host}:{port}/db/{graph_name}/index/{label}/{field}
It only creates 「vertex index」, when try to create 「edge index」 it failed.

**To Reproduce**
1.Post a request which create edge index with edge label.
2.It will then return 400 error.

**Expected behavior**
According to the description of this method, all index creation includes 「vertex index」、「edge index」.
So this api should apply to create edge index.

**Screenshots**
<img width="1409" alt="image" src="https://user-images.githubusercontent.com/45623625/190332533-4fa096e4-9d3a-473c-8a58-98ac2f334dab.png">
<img width="677" alt="image" src="https://user-images.githubusercontent.com/45623625/190332578-e2427621-6eed-4c1a-929c-2b0641394241.png">

**Environment:**
 - OS: Ubuntu 20.04 LTS (GNU/Linux 5.15.30-2-pve x86_64)
 - CPU: Intel(R) Xeon(R) Gold 5218R CPU @ 2.10GHz
 - Compiler: GCC 5.4.0

**Additional context**
Related Code:
<img width="914" alt="image" src="https://user-images.githubusercontent.com/45623625/190332754-7d06346d-668e-4440-ae19-09ed52b844de.png">

The bug here only deal with AddVertexIndex method, miss AddEdgeIndex senareo.
So fix code is to add a branch here.
I wonder if I can create a pr to fix this bug or just waiting for the next exciting version.🤔

**Comment by knightast** [comment]
Thank you for report. We suggest to use cypher to create edge/vertex index, restful api based on cpprestsdk will be removed in the future and use brpc's rest interface.
Refer to https://github.com/TuGraph-db/tugraph-db/blob/master/doc/zh-CN/7.community/3.roadmap.md
