### ISSUE TITLE
请问支持子图复制么

### ISSUE THREAD

**Issue by liseri** [TuGraph-db/tugraph-db#49]
请问支持子图复制么，我的需求是对子图做版本管理，想到的一种方法是将某子图整体复制给一个新的快照子图

**Comment by knightast** [comment]
No specific API yet, but you can use procedure api to do it yourself.

We have plan to add multi-graph api this year. 
https://github.com/TuGraph-db/tugraph-db/blob/master/doc/zh-CN/7.community/3.roadmap.md

**Comment by liseri** [comment]
thank you!
