### ISSUE TITLE
build failed with cannot find dependencies

### ISSUE THREAD

**Issue by codesigner** [TuGraph-db/tugraph-db#5]
Build failed with following error, seems deps/build_deps.sh does not handle all dependencies.

``
In file included from /home/codesigner/Data/tugraph-db/src/client/cpp/rpc/lgraph_rpc_client.cpp:5:
/home/codesigner/Data/tugraph-db/src/client/cpp/rpc/lgraph_rpc.h:11:10: fatal error: brpc/server.h: No such file or directory
   11 | #include "brpc/server.h"
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/CMakeFiles/liblgraph_rpc_client.dir/build.make:83: src/CMakeFiles/liblgraph_rpc_client.dir/client/cpp/rpc/lgraph_rpc_client.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[  2%] Building CXX object src/CMakeFiles/lgraph.dir/core/data_type.cpp.o
In file included from /home/codesigner/Data/tugraph-db/src/client/cpp/restful/rest_client.cpp:3:
/home/codesigner/Data/tugraph-db/src/client/cpp/restful/rest_client.h:7:10: fatal error: cpprest/json.h: No such file or directory
    7 | #include "cpprest/json.h"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/CMakeFiles/lgraph_rest_client.dir/build.make:83: src/CMakeFiles/lgraph_rest_client.dir/client/cpp/restful/rest_client.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[  2%] Building CXX object src/CMakeFiles/lgraph.dir/core/edge_index.cpp.o
In file included from /home/codesigner/Data/tugraph-db/src/db/galaxy.h:24,
                 from /home/codesigner/Data/tugraph-db/src/lgraph_api/lgraph_galaxy.cpp:4:
/home/codesigner/Data/tugraph-db/src/db/token_manager.h:9:10: fatal error: jwt-cpp/jwt.h: No such file or directory
    9 | #include "jwt-cpp/jwt.h"
      |          ^~~~~~~~~~~~~~~
`
``

In ci/images/centos7/Dockerfile, I find the brpc directory as copied to docker, so which brpc version do you use.
``
COPY brpc /brpc
RUN  cd /brpc && mkdir build && cd build \
     && cmake $CMAKE_OPT -DBUILD_UNIT_TESTS=0 .. && make -j && make install \
     && rm -rf /brpc*
``

**Comment by ljcui** [comment]
> 

Yes, the build scripts need to be improved. Using the latest version of brpc is ok.
