### ISSUE TITLE
「call db.addEdgeIndex」 fail

### ISSUE THREAD

**Issue by abstract-liu** [TuGraph-db/tugraph-db#50]
**Describe the bug**
The builtin procedure「DbAddEdgeIndex」fails when try to create new edge index.

**To Reproduce**
1. just add an edge index throw web-console, or cypher.
2. you can use my unit test to verify either.

**Expected behavior**
A new edge index should be created and no error.

**Screenshots**
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/45623625/190575013-0749c86d-4528-44ff-acd5-ce4df22787cd.png">

**Environment:**
- OS: Ubuntu 20.04 LTS (GNU/Linux 5.15.30-2-pve x86_64)
- CPU: Intel(R) Xeon(R) Gold 5218R CPU @ 2.10GHz
- Compiler: GCC 5.4.0 Debug mode

**Additional context**
Related code:
<img width="1091" alt="image" src="https://user-images.githubusercontent.com/45623625/190575445-f9cd7230-1a76-4b43-bafc-96a78db8a637.png">

The root cause is in edge_index.h, line 81.
It get the wrong order subtraction, which will cause a big n.

**Comment by ljcui** [comment]
Thanks，we have known about this issue before and a fix is in the works..

**Comment by abstract-liu** [comment]
ok, hope to see the next exciting version
