### ISSUE TITLE
How does TuGraph support vertex/edge deletion?

### ISSUE THREAD

**Issue by chenht2022** [TuGraph-db/tugraph-db#51]
Dear authors,

Thanks for releasing the source code of TuGraph. I am wondering how does TuGraph support vertex/edge deletion, since I cannot find it in the document. Do I have to stop the server and overwrite the entire graph to delete a small part of the graph? Or there is any online method to do so? Thanks!

**Comment by knightast** [comment]
TuGraph supports real time CRUD, and graph data are packed into KVs on LMDB, we will complete this part of design in the future. If you have further question, please go to https://github.com/TuGraph-db/tugraph-db/discussions
