### ISSUE TITLE
Cypher to add a edge is too slow

### ISSUE THREAD

**Issue by g00db0y0** [TuGraph-db/tugraph-db#55]
Adding EDGEs dynamically using sdk or cypher is very slow. Except lgraph_import --online, is there another way.

**Comment by abasi20** [comment]
it is a good way to call a storage procedure for insert edges.

**Comment by knightast** [comment]
If you want to add one edge in one transaction, throughput is a better measure than latency. 

You can also write cpp procedure to complete any task, which always get the best performance.
