### ISSUE TITLE
tugraph-explore.md中下载TuGraph Explore 镜像时无法下载

### ISSUE THREAD

**Issue by mollylanguange** [TuGraph-db/tugraph-db#59]
**Describe the bug**
tugraph-explore.md中下载TuGraph Explore 镜像：点击下载时无法下载

**To Reproduce**
1. Go to  doc-->zh-CH-->2.operating-->6.tools-->4.tugraph-explore.md

**Expected behavior**

**Screenshots**
![Uploading image.png…]()

**Environment:**
 - OS: [e.g. Ubuntu 18.04]
 - CPU: [e.g. Intel Xeon xxxx]
 - Compiler: [e.g. GCC 8.0]

**Additional context**

**Comment by KingSkyLi** [comment]
由于图探索的示例数据涉及隐私安全，所以暂时下线了，我们正在进行积极调整，重新上线后会及时通知大家。

**Comment by KingSkyLi** [comment]
As the sample data of Graph exploration concerns privacy and security, it is temporarily offline. We are making positive adjustments and will inform you when we get online again.

**Comment by knightast** [comment]
已重新上线 https://github.com/TuGraph-db/tugraph-explore
