### ISSUE TITLE
无法编译算法插件

### ISSUE THREAD

**Issue by Casithy** [TuGraph-db/tugraph-db#93]
我阅读了官方文档【1.tutorial】一节，根据文档提示进行Procedure编译与运行，将github【tugraph-db】仓库中plugins文件夹拷贝至服务器中，执行bash make_so.sh bfs，却提示找不到liblgraph.so文件

**Comment by knightast** [comment]
Seems solve by yourself :)

**Comment by Casithy** [comment]
是的，:)。
但后续将.so文件加载到tugraph-web后，需要添加的json不知道是什么格式，按照文档却报错。

`{
    "root_id":"0",
    "label":"movie",
    "field":"id"
}`

`data: Object
error_message: "Invalid iterator."
status: 500
statusText: "Internal Error"
headers: Object
config: Object
request: XMLHttpRequest`

**Comment by knightast** [comment]
看plugin的代码就能确定json的格式了，看报错是获取iterator失败，应该是 root_id 有问题，解析的不对或者图里没这个点

**Comment by Casithy** [comment]
谢谢您的解答！已经解决了，
`{ "root_id":21537, "label":"movie", "field":"ID" }`
但是错误变成了【Failed to convert field data [21537] into type STRING】

**Comment by knightast** [comment]
数字的引号还是得有，传参是按照字符串来的，你试试

{ "root_id":"1", "label":"movie", "field":"id" }
