### ISSUE TITLE
这个非常不稳定，莫名其妙就挂了

### ISSUE THREAD

**Issue by allensky708** [TuGraph-db/tugraph-db#95]
用了一天，容器会莫名的挂掉，正在使用的过程中挂掉，重启不来，数据没有挂载到其他地方，只能删除容器重新来过，重来两次就放弃了，极不稳定，也不会报什么异常

**Comment by knightast** [comment]
期间有什么操作？只跑demo?

**Comment by allensky708** [comment]
使用了样例图谱做一些查询，删除数据删除关系和节点，然后删除全部节点的时候就卡住了，然后容器服务会停掉，起不来，日志也看不到什么异常

**Comment by allensky708** [comment]
> 使用示例图做一些查询，删除数据删除样例关系和节点，然后删除所有节点的时候就卡住了，然后容器服务会停止掉，起不来，日志也看不到异常

**Comment by knightast** [comment]
用的就是movie的那个demo？删除全部节点用的什么语句？我们复现下看看

**Comment by knightast** [comment]
暂时无法复现，有类似的问题再重启讨论
