### ISSUE TITLE
是按计划完成了吗？我看更新文档 还停留在老版本 不是最新的3.3.1，很期待 Java OGM功能

### ISSUE THREAD

**Issue by GreenAppleOne** [TuGraph-db/tugraph-db#98]
规划：

7 | Java OGM | 开发中，预计2022.10
-- | -- | --
8 | REST接口从 cpprestsdk 迁移到 brpc | 计划中，预计2022.10

**Comment by GreenAppleOne** [comment]
两周过去了，咋还没有发布呢？

**Comment by KingSkyLi** [comment]
3.3.2版本已经发布，支持OGM
